CREATE TABLE IF NOT EXISTS users (
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    admin BOOLEAN DEFAULT FALSE,
    time_created TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
    time_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DELIMITER $$
    CREATE TRIGGER users_insert_trigger BEFORE INSERT ON users
    FOR EACH ROW
    BEGIN
        IF NEW.time_created = '0000-00-00 00:00:00' THEN
            SET NEW.time_created = NOW();
        END IF;
    END;
$$
DELIMITER ;
